# Generated by Django 4.1.7 on 2023-03-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='notes',
        ),
    ]
